// ─── AI Tools Database ───────────────────────────────────────────────────────
const AI_TOOLS = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    company: 'OpenAI',
    icon: '🤖',
    tagline: 'Conversational AI powering millions of workflows',
    category: 'llm',
    currentVersion: 'GPT-4o',
    previousVersion: 'GPT-4 Turbo',
    releaseDate: 'May 2024',
    website: 'https://chat.openai.com',
    features: [
      'GPT-4o multimodal (text, image, audio)',
      'Advanced data analysis & code interpreter',
      'Custom GPTs & GPT store',
      'Real-time web browsing',
      'Memory across conversations',
      'DALL-E 3 image generation built-in',
      'Voice mode (natural conversation)',
      'File uploads & document analysis',
    ],
    newFeatures: [
      'Canvas collaborative editor',
      'Projects with persistent memory',
      'Advanced Voice Mode with emotion',
      'Video & screen sharing in calls',
      'OpenAI o1 reasoning model access',
      'Scheduled tasks & automations',
    ],
    pricing: [
      { tier: 'Free', price: '$0', period: '/mo', features: ['GPT-4o mini', 'Limited GPT-4o', 'DALL-E basic', 'Limited memory'] },
      { tier: 'Plus', price: '$20', period: '/mo', features: ['Full GPT-4o', 'o1 access', 'DALL-E 3', 'Advanced analysis', '5× more messages'] },
      { tier: 'Pro', price: '$200', period: '/mo', features: ['Unlimited o1', 'o1 Pro mode', 'All features', 'Priority access'] },
      { tier: 'Team', price: '$30', period: '/user/mo', features: ['All Plus features', 'Team workspace', 'Admin controls', 'Data privacy'] },
      { tier: 'Enterprise', price: 'Custom', period: '', features: ['Custom limits', 'SSO', 'Compliance', 'SLA guarantee'] },
    ],
    versionDiff: {
      added: ['Canvas editor for real-time co-writing', 'Persistent Projects with memory', 'o1 pro reasoning mode', 'Video input support', 'Scheduled tasks'],
      removed: ['GPT-3.5 in free tier (replaced with 4o mini)'],
      changed: ['Faster response times (50% improvement)', 'Better instruction following', 'Longer context handling (128K tokens)'],
    },
    benefits: ['Save 3–5 hrs/day on writing tasks', 'Automate repetitive workflows', 'Instant expert-level answers', 'Code debugging in seconds'],
    score: { speed: 9, accuracy: 9, cost: 7, features: 10 },
  },

  {
    id: 'claude',
    name: 'Claude',
    company: 'Anthropic',
    icon: '🧠',
    tagline: 'The AI assistant focused on safety and helpfulness',
    category: 'llm',
    currentVersion: 'Claude 4 (Opus/Sonnet/Haiku)',
    previousVersion: 'Claude 3.5',
    releaseDate: '2025',
    website: 'https://claude.ai',
    features: [
      '200K token context window',
      'Advanced reasoning & analysis',
      'Code generation & debugging',
      'Document & PDF analysis',
      'Projects with persistent memory',
      'Artifacts (interactive outputs)',
      'Safety-first design',
      'Strong instruction following',
    ],
    newFeatures: [
      'Claude 4 Opus — top reasoning benchmark',
      'Extended thinking mode',
      'Computer use (GUI automation)',
      'Claude Code (coding agent)',
      'Improved tool use & agents',
      'Faster Haiku for cost-efficiency',
    ],
    pricing: [
      { tier: 'Free', price: '$0', period: '/mo', features: ['Claude Sonnet access', 'Limited daily messages', 'Basic Projects', 'Artifacts'] },
      { tier: 'Pro', price: '$20', period: '/mo', features: ['Claude Opus', 'Priority access', '5× more messages', 'Projects & memory', 'Early features'] },
      { tier: 'Team', price: '$30', period: '/user/mo', features: ['All Pro features', 'Team workspace', 'Admin console'] },
      { tier: 'API', price: 'Usage', period: 'based', features: ['Opus: $15/M tokens', 'Sonnet: $3/M', 'Haiku: $0.25/M'] },
    ],
    versionDiff: {
      added: ['Extended thinking (deep reasoning)', 'Computer use capability', 'Claude Code autonomous agent', 'Improved multilingual support'],
      removed: ['Claude 2 (deprecated)'],
      changed: ['Longer context support', 'Better code quality', 'Faster Haiku model', 'Improved safety filters'],
    },
    benefits: ['Best-in-class for long document analysis', 'Trustworthy & transparent answers', 'Excellent for legal/medical content', 'Code automation end-to-end'],
    score: { speed: 8, accuracy: 10, cost: 8, features: 9 },
  },

  {
    id: 'gemini',
    name: 'Gemini',
    company: 'Google',
    icon: '💎',
    tagline: 'Google\'s most capable multimodal AI',
    category: 'llm',
    currentVersion: 'Gemini 2.5 Pro',
    previousVersion: 'Gemini 1.5 Pro',
    releaseDate: 'Mar 2025',
    website: 'https://gemini.google.com',
    features: [
      '1M+ token context window',
      'Native multimodal (text, image, audio, video)',
      'Deep Google Search integration',
      'Google Workspace integration',
      'Code execution sandbox',
      'YouTube video understanding',
      'Real-time information access',
      'Imagen 3 image generation',
    ],
    newFeatures: [
      'Gemini 2.5 Pro — best reasoning',
      'Deep Research feature',
      'Gems (custom AI agents)',
      'Notebook LM integration',
      'Video generation (Veo 2)',
      '2M context window (experimental)',
    ],
    pricing: [
      { tier: 'Free', price: '$0', period: '/mo', features: ['Gemini 1.5 Flash', 'Limited Gemini Pro', 'Basic tools'] },
      { tier: 'Advanced', price: '$19.99', period: '/mo', features: ['Gemini 2.5 Pro', 'Deep Research', 'Gems', '2TB Drive', 'Priority'] },
      { tier: 'API Free', price: '$0', period: '', features: ['60 req/min', 'Gemini 1.5 Flash', 'Personal use only'] },
      { tier: 'API Paid', price: '$3.50', period: '/M tokens', features: ['Gemini 2.5 Pro', 'Batch discount', 'SLA'] },
    ],
    versionDiff: {
      added: ['Deep Research multi-step agent', 'Gems custom agents', 'Video generation Veo 2', '2M context window', 'Thinking mode'],
      removed: ['Bard branding', 'Gemini Ultra tier'],
      changed: ['Renamed to 2.5 series', 'Better coding ability', '10× faster inference', 'Improved reasoning scores'],
    },
    benefits: ['Seamless Google Workspace integration', 'Best for research with web access', 'Largest context of any model', 'Free tier very generous'],
    score: { speed: 9, accuracy: 9, cost: 9, features: 9 },
  },

  {
    id: 'midjourney',
    name: 'Midjourney',
    company: 'Midjourney Inc.',
    icon: '🎨',
    tagline: 'World-leading AI image generation',
    category: 'image',
    currentVersion: 'V7',
    previousVersion: 'V6.1',
    releaseDate: 'Mar 2025',
    website: 'https://midjourney.com',
    features: [
      'Photorealistic image generation',
      'Consistent character creation',
      'Style reference (--sref)',
      'Image-to-image transformation',
      'Upscaling to 2K/4K',
      'Inpainting & vary (region)',
      'Web interface (no Discord needed)',
      'Personalization profiles',
    ],
    newFeatures: [
      'V7 — best photorealism yet',
      'Draft mode (10× faster)',
      'Omni-reference (character consistency)',
      'Personalization learning',
      'Image prompt weights V7',
    ],
    pricing: [
      { tier: 'Basic', price: '$10', period: '/mo', features: ['200 GPU mins/mo', 'Web access', '3 concurrent jobs'] },
      { tier: 'Standard', price: '$30', period: '/mo', features: ['15h fast GPU', 'Unlimited relax', 'Stealth off'] },
      { tier: 'Pro', price: '$60', period: '/mo', features: ['30h fast GPU', 'Stealth mode', '12 concurrent'] },
      { tier: 'Mega', price: '$120', period: '/mo', features: ['60h fast GPU', 'Max concurrent', 'Priority queue'] },
    ],
    versionDiff: {
      added: ['Draft mode for rapid iteration', 'Omni-reference multi-subject', 'Better text in images', 'Style consistency across batches'],
      removed: ['Discord-only requirement'],
      changed: ['Improved skin texture rendering', 'Better lighting simulation', 'More accurate prompt adherence'],
    },
    benefits: ['Professional-quality art in seconds', 'Eliminate stock photo costs', 'Brand identity assets', 'Marketing visuals at scale'],
    score: { speed: 7, accuracy: 9, cost: 7, features: 9 },
  },

  {
    id: 'copilot',
    name: 'GitHub Copilot',
    company: 'Microsoft / GitHub',
    icon: '👨‍💻',
    tagline: 'AI pair programmer for every developer',
    category: 'code',
    currentVersion: 'Copilot Enterprise + Workspace',
    previousVersion: 'Copilot X',
    releaseDate: '2024–2025',
    website: 'https://github.com/features/copilot',
    features: [
      'Inline code completion',
      'Multi-file edits',
      'Pull request summaries',
      'Code explanation & chat',
      'Test generation',
      'Security vulnerability detection',
      'CLI assistant',
      'IDE integration (VS Code, JetBrains, etc.)',
    ],
    newFeatures: [
      'Copilot Workspace (autonomous agent)',
      'Claude 3.5 & GPT-4o model choice',
      'Copilot Extensions (custom agents)',
      'Code review agent',
      'Issue-to-PR automation',
      'Agent mode in VS Code',
    ],
    pricing: [
      { tier: 'Free', price: '$0', period: '/mo', features: ['2000 completions/mo', '50 chat/mo', 'VS Code only'] },
      { tier: 'Pro', price: '$10', period: '/mo', features: ['Unlimited completions', 'All IDEs', 'GPT-4o & Claude'] },
      { tier: 'Business', price: '$19', period: '/user/mo', features: ['All Pro', 'Admin controls', 'Audit logs', 'IP indemnity'] },
      { tier: 'Enterprise', price: '$39', period: '/user/mo', features: ['Workspace', 'Custom models', 'Fine-tuning', 'SLA'] },
    ],
    versionDiff: {
      added: ['Copilot Workspace (end-to-end dev agent)', 'Model picker (GPT-4o/Claude)', 'Extensions API', 'Agent mode multi-step', 'PR auto-review'],
      removed: ['Codex model (replaced with GPT-4o)'],
      changed: ['Better context awareness', 'Faster completions', 'More language support (200+)', 'Improved security scanning'],
    },
    benefits: ['55% faster code writing', 'Reduce debugging time by 40%', 'Onboard new devs faster', 'Automate PR reviews'],
    score: { speed: 10, accuracy: 8, cost: 9, features: 9 },
  },

  {
    id: 'sora',
    name: 'Sora',
    company: 'OpenAI',
    icon: '🎬',
    tagline: 'Realistic AI video generation from text',
    category: 'video',
    currentVersion: 'Sora Turbo',
    previousVersion: 'Sora Research Preview',
    releaseDate: 'Dec 2024',
    website: 'https://sora.com',
    features: [
      'Text-to-video generation (up to 20s)',
      '1080p video quality',
      'Image-to-video conversion',
      'Video-to-video transformation',
      'Storyboard tool',
      'Loop & blend videos',
      'Re-cut & remix tools',
      'Consistent characters across scenes',
    ],
    newFeatures: [
      'Sora Turbo — 4× faster generation',
      'Director mode (camera controls)',
      'Sound effects generation',
      '4K upscaling',
      'Multi-shot story generation',
    ],
    pricing: [
      { tier: 'Plus', price: '$20', period: '/mo (ChatGPT)', features: ['50 priority videos', '1000 relax videos', '720p max', '5s max'] },
      { tier: 'Pro', price: '$200', period: '/mo', features: ['500 priority videos', 'Unlimited relax', '1080p', '20s max', 'Watermark free'] },
    ],
    versionDiff: {
      added: ['Turbo mode (4× faster)', 'Director camera controls', 'Sound generation', 'Storyboard editor', '4K option'],
      removed: ['Research preview waitlist'],
      changed: ['Better physics simulation', 'Improved text rendering in video', 'More consistent character looks'],
    },
    benefits: ['Eliminate video production costs', 'Rapid concept visualization', 'Marketing videos in minutes', 'Training & demo content'],
    score: { speed: 7, accuracy: 8, cost: 5, features: 9 },
  },

  {
    id: 'perplexity',
    name: 'Perplexity AI',
    company: 'Perplexity AI',
    icon: '🔍',
    tagline: 'AI-powered answer engine with citations',
    category: 'productivity',
    currentVersion: 'Perplexity Pro 2025',
    previousVersion: 'Perplexity 2024',
    releaseDate: 'Jan 2025',
    website: 'https://perplexity.ai',
    features: [
      'Real-time web search + AI answers',
      'Source citations for every claim',
      'Deep Research mode (multi-step)',
      'Pro Search (complex queries)',
      'File upload & analysis',
      'Image generation (DALL-E, SDXL)',
      'Internal knowledge search',
      'Perplexity Pages (reports)',
    ],
    newFeatures: [
      'Assistant mode (full agent)',
      'Perplexity for Business (internal search)',
      'Sonar API for developers',
      'Shopping assistant with buy buttons',
      'Real-time financial data',
    ],
    pricing: [
      { tier: 'Free', price: '$0', period: '/mo', features: ['5 Pro searches/day', 'GPT-3.5 quality', 'Basic search'] },
      { tier: 'Pro', price: '$20', period: '/mo', features: ['Unlimited Pro search', 'GPT-4o / Claude', 'Deep Research', 'File uploads', '$5 API credits'] },
      { tier: 'Enterprise', price: 'Custom', period: '', features: ['Internal search', 'SSO', 'Data privacy', 'Custom integrations'] },
    ],
    versionDiff: {
      added: ['Assistant mode (task execution)', 'Shopping integration', 'Internal enterprise search', 'Sonar API', 'Real-time finance data'],
      removed: [],
      changed: ['Better citation quality', 'Multi-model support', 'Faster response times', 'Improved deep research accuracy'],
    },
    benefits: ['Replace 80% of manual research', 'Trusted answers with sources', 'Faster due diligence', 'Real-time market intelligence'],
    score: { speed: 10, accuracy: 8, cost: 9, features: 8 },
  },

  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    company: 'ElevenLabs',
    icon: '🔊',
    tagline: 'Most realistic AI voice generation platform',
    category: 'voice',
    currentVersion: 'V3 Flash',
    previousVersion: 'V2 Turbo',
    releaseDate: '2025',
    website: 'https://elevenlabs.io',
    features: [
      'Voice cloning (3 seconds of audio)',
      '3000+ voices in 32 languages',
      'Text-to-speech API',
      'Speech-to-speech conversion',
      'Dubbing & translation',
      'AI audio book narration',
      'Real-time voice streaming',
      'Conversational AI voices',
    ],
    newFeatures: [
      'V3 Flash — ultra-low latency (75ms)',
      'Emotional voice control',
      'Conversational AI platform',
      'Sound effects generation',
      'Voice isolation',
      'Projects (long-form audio)',
    ],
    pricing: [
      { tier: 'Free', price: '$0', period: '/mo', features: ['10K chars/mo', '3 custom voices', 'API access'] },
      { tier: 'Starter', price: '$5', period: '/mo', features: ['30K chars', '10 voices', 'Commercial use'] },
      { tier: 'Creator', price: '$22', period: '/mo', features: ['100K chars', '30 voices', 'Projects', 'Dubbing'] },
      { tier: 'Pro', price: '$99', period: '/mo', features: ['500K chars', '160 voices', 'Priority', 'Analytics'] },
      { tier: 'Enterprise', price: 'Custom', period: '', features: ['Unlimited', 'SLA', 'Custom models'] },
    ],
    versionDiff: {
      added: ['V3 Flash low-latency model', 'Sound effects generation', 'Conversational AI hosting', 'Voice isolation tool', 'Emotional control parameters'],
      removed: ['V1 models (deprecated)'],
      changed: ['Latency reduced from 300ms to 75ms', 'More natural prosody', 'Better multilingual quality'],
    },
    benefits: ['Eliminate voiceover studio costs', 'Scale content to 32 languages', 'Consistent brand voice 24/7', 'Accessible content for all'],
    score: { speed: 9, accuracy: 9, cost: 8, features: 9 },
  },

  {
    id: 'cursor',
    name: 'Cursor',
    company: 'Anysphere',
    icon: '⌨️',
    tagline: 'The AI-first code editor built for speed',
    category: 'code',
    currentVersion: '0.45',
    previousVersion: '0.40',
    releaseDate: '2025',
    website: 'https://cursor.sh',
    features: [
      'AI-powered code completion',
      'Natural language to code (Cmd+K)',
      'Codebase chat (understand entire repo)',
      'Multi-file edits with AI',
      'Automatic bug fixing',
      'VS Code compatible',
      'Privacy mode',
      'Custom AI rules (.cursorrules)',
    ],
    newFeatures: [
      'Cursor Agent — autonomous coding',
      'Background agents (parallel tasks)',
      'Claude 3.7 & GPT-4o integration',
      'Composer with multiple files',
      'Bug finder mode',
      'Shadow workspace',
    ],
    pricing: [
      { tier: 'Hobby', price: '$0', period: '/mo', features: ['2000 completions', '50 slow premium', 'GPT-4o mini'] },
      { tier: 'Pro', price: '$20', period: '/mo', features: ['Unlimited completions', '500 fast premium', 'Claude & GPT-4o', 'Agent mode'] },
      { tier: 'Business', price: '$40', period: '/user/mo', features: ['All Pro', 'Admin controls', 'SAML SSO', 'Enforced privacy'] },
    ],
    versionDiff: {
      added: ['Background agents for parallel work', 'Shadow workspace (no risk edits)', 'Notepads (knowledge bases)', 'Bug finder', 'Model context protocol support'],
      removed: [],
      changed: ['Faster autocomplete (2× speedup)', 'Better multi-file coherence', 'Improved context from full codebase'],
    },
    benefits: ['10× faster feature development', 'Understand unfamiliar codebases instantly', 'Refactor legacy code safely', 'Junior dev productivity at senior level'],
    score: { speed: 10, accuracy: 9, cost: 9, features: 10 },
  },

  {
    id: 'runway',
    name: 'Runway ML',
    company: 'Runway',
    icon: '🎭',
    tagline: 'Professional AI video creation suite',
    category: 'video',
    currentVersion: 'Gen-3 Alpha Turbo',
    previousVersion: 'Gen-2',
    releaseDate: '2024',
    website: 'https://runwayml.com',
    features: [
      'Text-to-video Gen-3 Alpha',
      'Image-to-video generation',
      'Video-to-video style transfer',
      'Inpainting & background removal',
      'Motion brush control',
      'Lip sync generation',
      'Act-One actor animation',
      '4K upscaling',
    ],
    newFeatures: [
      'Gen-3 Turbo (3× faster)',
      'Act-One — expressive character animation',
      'Frames (image-to-video control)',
      'Camera control presets',
      'Custom model training',
    ],
    pricing: [
      { tier: 'Free', price: '$0', period: '/mo', features: ['125 credits', 'Watermarked', 'Basic tools'] },
      { tier: 'Standard', price: '$15', period: '/mo', features: ['625 credits', 'No watermark', 'Gen-3'] },
      { tier: 'Pro', price: '$35', period: '/mo', features: ['2250 credits', 'Priority', 'All tools'] },
      { tier: 'Unlimited', price: '$95', period: '/mo', features: ['Unlimited (relaxed)', 'Priority queue', 'Custom models'] },
    ],
    versionDiff: {
      added: ['Act-One expressive animation', 'Frames precise video control', 'Camera presets', 'Gen-3 Turbo speed mode'],
      removed: ['Gen-1 model'],
      changed: ['Gen-3 Alpha: far more realistic output', 'Better motion coherence', 'Improved prompt understanding'],
    },
    benefits: ['Professional VFX without studios', 'Rapid storyboarding & previs', 'Marketing video production', 'Film & TV concept visualization'],
    score: { speed: 7, accuracy: 8, cost: 6, features: 9 },
  },

  {
    id: 'notionai',
    name: 'Notion AI',
    company: 'Notion',
    icon: '📝',
    tagline: 'AI-powered workspace for notes, docs & projects',
    category: 'productivity',
    currentVersion: 'Notion AI 2025',
    previousVersion: 'Notion AI 2023',
    releaseDate: '2025',
    website: 'https://notion.so',
    features: [
      'AI writing & editing in docs',
      'Q&A over your entire workspace',
      'Meeting summary & action items',
      'Database auto-fill with AI',
      'Translate to 100+ languages',
      'AI templates & generation',
      'Connected search (Slack, Drive)',
      'AI project planning',
    ],
    newFeatures: [
      'Notion AI connectors (Slack, GitHub, Drive)',
      'Personalized AI (learns your style)',
      'AI meetings with auto-summary',
      'Workflow automations with AI',
    ],
    pricing: [
      { tier: 'Free', price: '$0', period: '/mo', features: ['20 AI responses/mo', 'Basic workspace'] },
      { tier: 'Plus', price: '$10', period: '/mo', features: ['Unlimited AI', 'Full workspace', 'Guests'] },
      { tier: 'Business', price: '$18', period: '/user/mo', features: ['All Plus', 'SAML', 'Advanced AI', 'Connectors'] },
      { tier: 'Enterprise', price: 'Custom', period: '', features: ['Custom AI models', 'Compliance', 'SLA'] },
    ],
    versionDiff: {
      added: ['External connectors (Slack, Drive, GitHub)', 'Personalized AI learning', 'Meeting AI integration', 'Workflow automation'],
      removed: [],
      changed: ['Faster AI responses', 'Better context from workspace', 'Multi-language improved'],
    },
    benefits: ['Eliminate meeting notes 100%', 'Find any company knowledge instantly', 'Onboard employees 2× faster', 'Automate status updates'],
    score: { speed: 9, accuracy: 8, cost: 9, features: 8 },
  },

  {
    id: 'stablediffusion',
    name: 'Stable Diffusion (FLUX)',
    company: 'Stability AI / Black Forest Labs',
    icon: '🖼️',
    tagline: 'Open-source image AI with professional quality',
    category: 'image',
    currentVersion: 'FLUX 1.1 Pro',
    previousVersion: 'SD XL',
    releaseDate: '2024',
    website: 'https://stability.ai',
    features: [
      'FLUX 1.1 Pro ultra-quality',
      'Photorealistic generation',
      'Open-source & self-hostable',
      'API access via Stability AI',
      'ControlNet compatibility',
      'Inpainting & outpainting',
      'Style LoRA fine-tuning',
      'Unlimited local use',
    ],
    newFeatures: [
      'FLUX 1.1 Pro — beats Midjourney V6',
      'FLUX Ultra (4MP output)',
      'Real-time generation mode',
      'Fill & expand tools',
      'Redux (image variation)',
    ],
    pricing: [
      { tier: 'Open Source', price: 'Free', period: '', features: ['Self-hosted', 'Unlimited use', 'Full control'] },
      { tier: 'API Starter', price: '$0.003', period: '/image', features: ['FLUX 1.1', 'Fast', 'Commercial ok'] },
      { tier: 'API Pro', price: '$0.055', period: '/image', features: ['FLUX Ultra', '4MP', 'Priority'] },
    ],
    versionDiff: {
      added: ['FLUX 1.1 Pro architecture', 'FLUX Ultra 4MP', 'Real-time generation', 'Redux variation tool', 'Depth & edge controls'],
      removed: ['SD 1.5 (legacy)'],
      changed: ['10× better text rendering', 'More photorealistic faces', 'Better anatomy & hands', 'Faster generation (2×)'],
    },
    benefits: ['Zero ongoing cost if self-hosted', 'Complete creative control', 'No content restrictions (with own hardware)', 'Custom model fine-tuning'],
    score: { speed: 8, accuracy: 9, cost: 10, features: 9 },
  },
];

// ─── Industry Use Cases ──────────────────────────────────────────────────────
const USE_CASES = [
  {
    industry: 'healthcare',
    industryLabel: 'Healthcare',
    icon: '🏥',
    department: 'Clinical Operations',
    tool: 'Claude',
    toolIcon: '🧠',
    scenario: 'Analyzing patient records, research papers, and clinical notes to assist physicians in diagnosis and treatment planning.',
    realExample: 'A hospital uses Claude to process 500-page clinical trial documents in minutes, extracting key findings and flagging drug interactions for pharmacists.',
    benefits: [
      'Summarize patient history from EHR in 30 seconds',
      'Flag potential drug interactions automatically',
      'Draft clinical notes from physician voice memos',
      'Accelerate literature review for evidence-based medicine',
    ],
    roi: '40% faster diagnoses',
    timeSaved: '3hrs/day per physician',
    comparedTo: 'Manual EHR review takes 4–6 hours',
  },
  {
    industry: 'healthcare',
    industryLabel: 'Healthcare',
    icon: '🏥',
    department: 'Medical Imaging',
    tool: 'FLUX / Stable Diffusion',
    toolIcon: '🖼️',
    scenario: 'Generating synthetic medical training images for AI model training without patient privacy concerns.',
    realExample: 'Radiology AI startup generates 50,000 synthetic X-ray images of rare conditions to train diagnostic models.',
    benefits: [
      'Create privacy-safe training datasets',
      'Simulate rare conditions for model training',
      'Generate patient education visuals',
      'Accelerate FDA submission with synthetic data',
    ],
    roi: '80% cheaper data collection',
    timeSaved: '6 months per dataset',
    comparedTo: 'Manual annotation of real scans: $200K+',
  },
  {
    industry: 'finance',
    industryLabel: 'Finance',
    icon: '💰',
    department: 'Research & Analysis',
    tool: 'Perplexity AI',
    toolIcon: '🔍',
    scenario: 'Real-time financial research, earnings call analysis, and market intelligence gathering with cited sources.',
    realExample: 'Investment bank analysts use Perplexity Pro to research 20 companies per day instead of 5, with automatic source citations for compliance.',
    benefits: [
      'Research 4× more companies daily',
      'Automatic source citations for compliance',
      'Real-time market news synthesis',
      'Earnings call summaries in 2 minutes',
    ],
    roi: '75% faster research cycles',
    timeSaved: '5hrs/day per analyst',
    comparedTo: 'Bloomberg terminal searches: $2000/mo per user',
  },
  {
    industry: 'finance',
    industryLabel: 'Finance',
    icon: '💰',
    department: 'Software Development',
    tool: 'GitHub Copilot',
    toolIcon: '👨‍💻',
    scenario: 'Accelerating development of trading algorithms, risk models, and compliance automation systems.',
    realExample: 'A fintech company reduced development time for a new risk scoring API from 8 weeks to 3 weeks using Copilot Enterprise with custom models trained on their codebase.',
    benefits: [
      '55% faster code delivery',
      'Auto-generate unit tests for regulatory compliance',
      'Understand legacy COBOL code instantly',
      'Auto-document APIs for auditors',
    ],
    roi: '62% productivity increase',
    timeSaved: '4hrs/dev/day',
    comparedTo: 'Senior dev billing at $150–250/hr',
  },
  {
    industry: 'education',
    industryLabel: 'Education',
    icon: '🎓',
    department: 'Curriculum Design',
    tool: 'ChatGPT',
    toolIcon: '🤖',
    scenario: 'Creating personalized learning materials, assessments, and lesson plans adapted to different learning levels.',
    realExample: 'A K-12 school district uses ChatGPT to generate differentiated worksheets for 3 reading levels simultaneously, saving teachers 10 hours per week.',
    benefits: [
      'Generate 3-level differentiated content instantly',
      'Create quizzes with answer keys automatically',
      'Translate materials to 50+ languages',
      'Design rubrics aligned to standards',
    ],
    roi: '10hrs saved/teacher/week',
    timeSaved: '10hrs/week per teacher',
    comparedTo: 'Curriculum writers: $80–120/hr',
  },
  {
    industry: 'education',
    industryLabel: 'Education',
    icon: '🎓',
    department: 'E-Learning Production',
    tool: 'ElevenLabs',
    toolIcon: '🔊',
    scenario: 'Creating multilingual audio for online courses, lectures, and accessible content without recording studios.',
    realExample: 'Online university narrates 500-hour course library into 12 languages in 2 weeks using ElevenLabs, reaching 10M more potential students globally.',
    benefits: [
      'Narrate entire courses without recording studios',
      'Instant translation to 32 languages',
      'Consistent voice across all content',
      'ADA accessibility compliance at scale',
    ],
    roi: '90% production cost reduction',
    timeSaved: '2 weeks per course',
    comparedTo: 'Professional voiceover: $400–1000/hr',
  },
  {
    industry: 'retail',
    industryLabel: 'Retail & E-Commerce',
    icon: '🛒',
    department: 'Marketing & Content',
    tool: 'ChatGPT + Midjourney',
    toolIcon: '🤖',
    scenario: 'Generating product descriptions, ad copy, and lifestyle imagery for thousands of SKUs at scale.',
    realExample: 'Fashion retailer generates unique product descriptions for 50,000 SKUs and matching lifestyle images in 3 days, replacing 6-month content production cycles.',
    benefits: [
      'Generate 1000 product descriptions per hour',
      'A/B test ad copy variations instantly',
      'Create lifestyle imagery without photoshoots',
      'Personalize content for each customer segment',
    ],
    roi: '300% content output increase',
    timeSaved: '6 months per catalog',
    comparedTo: 'Traditional catalog production: $500K+',
  },
  {
    industry: 'legal',
    industryLabel: 'Legal',
    icon: '⚖️',
    department: 'Contract Review',
    tool: 'Claude',
    toolIcon: '🧠',
    scenario: 'Reviewing contracts, flagging risky clauses, and summarizing legal documents for faster deal closure.',
    realExample: 'Law firm reviews 200-page M&A agreement in 15 minutes using Claude, identifying 23 risk clauses that previously took a paralegal 2 days.',
    benefits: [
      'Review 200-page contract in 15 minutes',
      'Flag non-standard clauses automatically',
      'Compare against standard templates',
      'Summarize obligations & deadlines',
    ],
    roi: '70% faster contract review',
    timeSaved: '2 days per contract',
    comparedTo: 'Paralegal billing: $150–300/hr',
  },
  {
    industry: 'marketing',
    industryLabel: 'Marketing',
    icon: '📣',
    department: 'Video Production',
    tool: 'Sora + Runway',
    toolIcon: '🎬',
    scenario: 'Creating professional marketing videos, product demos, and social content without production crews.',
    realExample: 'SaaS company creates 50 unique product demo videos for different industry verticals in 1 week, previously requiring $200K in video production per year.',
    benefits: [
      'Create 50 video variations in 1 week',
      'Test different messaging without reshoots',
      'Localize video content for each market',
      'Generate explainer videos from product specs',
    ],
    roi: '90% video cost reduction',
    timeSaved: '3 months per campaign',
    comparedTo: 'Video production agency: $10K–100K per video',
  },
  {
    industry: 'marketing',
    industryLabel: 'Marketing',
    icon: '📣',
    department: 'Research & Intelligence',
    tool: 'Perplexity AI',
    toolIcon: '🔍',
    scenario: 'Competitive intelligence, trend monitoring, and campaign research with real-time web data.',
    realExample: 'Marketing agency monitors 50 competitors daily and delivers weekly intelligence reports to clients in 2 hours instead of 2 days.',
    benefits: [
      'Monitor competitors in real-time',
      'Identify emerging trends before competitors',
      'Research campaign ideas with cited data',
      'Track brand mentions across the web',
    ],
    roi: '5× more intelligence delivered',
    timeSaved: '12hrs/week per analyst',
    comparedTo: 'Market research firms: $50K–200K per study',
  },
  {
    industry: 'engineering',
    industryLabel: 'Engineering & Tech',
    icon: '⚙️',
    department: 'Software Development',
    tool: 'Cursor',
    toolIcon: '⌨️',
    scenario: 'Full-stack development with AI pair programming for feature development, refactoring, and debugging.',
    realExample: 'Startup builds entire MVP in 3 weeks instead of 3 months using Cursor with Claude 3.7, with one engineer handling the work of a full 5-person team.',
    benefits: [
      'Write features 10× faster with AI agents',
      'Understand entire legacy codebase in minutes',
      'Refactor 10,000-line files safely',
      'Generate comprehensive tests automatically',
    ],
    roi: '10× development velocity',
    timeSaved: '6hrs/dev/day',
    comparedTo: 'Traditional development: $150–250/hr per developer',
  },
  {
    industry: 'hr',
    industryLabel: 'Human Resources',
    icon: '👥',
    department: 'Talent Acquisition',
    tool: 'ChatGPT + Notion AI',
    toolIcon: '🤖',
    scenario: 'Streamlining recruitment with AI-generated job descriptions, interview questions, and candidate evaluation frameworks.',
    realExample: 'HR team at 500-person company reduces time-to-hire from 45 days to 20 days by using AI for JD creation, initial screening, and structured interview guides.',
    benefits: [
      'Write compelling job descriptions in 5 minutes',
      'Generate role-specific interview guides',
      'Summarize candidate feedback for committees',
      'Create onboarding materials automatically',
    ],
    roi: '55% faster time-to-hire',
    timeSaved: '25 days per hire',
    comparedTo: 'Recruitment agencies: 15–25% of first-year salary',
  },
];

// ─── Curated AI News (Supplementary Static Data) ─────────────────────────────
const STATIC_NEWS = [
  {
    id: 'n1',
    title: 'OpenAI Launches GPT-5 with Unified Reasoning and Multimodal Capabilities',
    description: 'OpenAI\'s GPT-5 merges the reasoning strengths of the o-series with multimodal fluency, delivering significantly improved performance across coding, math, science, and creative tasks in a single unified model.',
    source: 'openai',
    sourceLabel: 'OpenAI',
    date: '2026-05-20',
    tags: ['GPT-5', 'reasoning', 'multimodal', 'OpenAI'],
    url: 'https://openai.com/blog',
    category: 'Model Release',
  },
  {
    id: 'n2',
    title: 'Google Gemini Ultra 2 Sets New State-of-the-Art Across All Major Benchmarks',
    description: 'Gemini Ultra 2 from Google DeepMind achieves top scores on MMLU, HumanEval, and MATH benchmarks. The model features a 2-million token context window and native real-time video understanding.',
    source: 'google',
    sourceLabel: 'Google',
    date: '2026-05-14',
    tags: ['Gemini', 'benchmark', 'multimodal', 'DeepMind'],
    url: 'https://deepmind.google',
    category: 'Model Release',
  },
  {
    id: 'n3',
    title: 'Anthropic Claude 4 Opus Tops Coding & Safety Leaderboards',
    description: 'Anthropic\'s Claude 4 Opus excels on SWE-bench and achieves the highest Constitutional AI safety scores to date. New features include extended tool use, computer control, and a 500K token context window.',
    source: 'anthropic',
    sourceLabel: 'Anthropic',
    date: '2026-05-08',
    tags: ['Claude 4', 'safety', 'coding', 'Anthropic'],
    url: 'https://anthropic.com/news',
    category: 'Model Release',
  },
  {
    id: 'n4',
    title: 'Meta Llama 4 Maverick Becomes Most Downloaded Open-Source AI Model',
    description: 'Meta\'s Llama 4 Maverick surpasses 100 million downloads on Hugging Face, becoming the dominant open-source AI model with best-in-class multilingual support and a 1-million token context window.',
    source: 'meta',
    sourceLabel: 'Meta AI',
    date: '2026-04-30',
    tags: ['Llama 4', 'open-source', 'Meta', 'multilingual'],
    url: 'https://ai.meta.com',
    category: 'Open Source',
  },
  {
    id: 'n5',
    title: 'Microsoft Copilot Agents Now Automate Full Business Workflows End-to-End',
    description: 'Microsoft 365 Copilot Wave 3 introduces fully autonomous agents that can manage email threads, schedule meetings, generate reports, and update CRM systems without human intervention.',
    source: 'microsoft',
    sourceLabel: 'Microsoft',
    date: '2026-04-22',
    tags: ['Copilot', 'agents', 'Microsoft 365', 'automation'],
    url: 'https://microsoft.com/ai',
    category: 'Product Launch',
  },
  {
    id: 'n6',
    title: 'Midjourney V7 Achieves Photorealistic Video Generation at 4K Resolution',
    description: 'Midjourney\'s V7 model now supports video generation up to 4K resolution with temporal consistency. The update also brings a new real-time collaborative canvas for team-based creative projects.',
    source: 'tools',
    sourceLabel: 'AI Tools',
    date: '2026-04-15',
    tags: ['Midjourney', 'video AI', 'V7', 'photorealism'],
    url: 'https://midjourney.com',
    category: 'Tool Launch',
  },
  {
    id: 'n7',
    title: 'ElevenLabs Launches Real-Time Voice Cloning API with Emotion Control',
    description: 'ElevenLabs\' new Voice Design API lets developers clone any voice from 10 seconds of audio and control emotional tone in real-time, enabling natural-sounding AI assistants and dubbing at scale.',
    source: 'tools',
    sourceLabel: 'AI Tools',
    date: '2026-04-08',
    tags: ['ElevenLabs', 'voice AI', 'API', 'emotion'],
    url: 'https://elevenlabs.io',
    category: 'Feature Update',
  },
  {
    id: 'n8',
    title: 'OpenAI Sora 2 Generates Cinematic 10-Minute Videos with Director Mode',
    description: 'Sora 2 supports up to 10 minutes of high-fidelity video with controllable camera angles, scene transitions, and character consistency. Pro users get priority access with 4K export.',
    source: 'openai',
    sourceLabel: 'OpenAI',
    date: '2026-03-28',
    tags: ['Sora', 'video AI', 'OpenAI', 'creative'],
    url: 'https://sora.com',
    category: 'Feature Update',
  },
  {
    id: 'n9',
    title: 'Cursor 1.0 Ships: AI Pair Programmer with Full Codebase Awareness',
    description: 'Cursor 1.0 reaches general availability with full repo-level understanding, multi-file edits, background agents that run tests automatically, and a new Shadow Mode for safe AI-driven refactors.',
    source: 'tools',
    sourceLabel: 'AI Tools',
    date: '2026-03-18',
    tags: ['Cursor', 'coding', 'agents', 'IDE'],
    url: 'https://cursor.sh',
    category: 'Product Launch',
  },
  {
    id: 'n10',
    title: 'Google DeepMind AlphaFold 4 Predicts Drug-Target Interactions with 95% Accuracy',
    description: 'AlphaFold 4 dramatically accelerates drug discovery by predicting how candidate molecules bind to protein targets with unprecedented accuracy, cutting early-stage research time from years to weeks.',
    source: 'google',
    sourceLabel: 'Google',
    date: '2026-03-10',
    tags: ['AlphaFold', 'drug discovery', 'DeepMind', 'research'],
    url: 'https://deepmind.google',
    category: 'Research Breakthrough',
  },
  {
    id: 'n11',
    title: 'Perplexity AI Pro Adds Agentic Research Mode with Auto-Citations',
    description: 'Perplexity\'s new Research Mode autonomously runs multi-step web research, synthesizes findings from dozens of sources, and generates fully cited reports in seconds — now integrated into enterprise plans.',
    source: 'tools',
    sourceLabel: 'AI Tools',
    date: '2026-03-02',
    tags: ['Perplexity', 'research', 'agents', 'citations'],
    url: 'https://perplexity.ai',
    category: 'Feature Launch',
  },
  {
    id: 'n12',
    title: 'Stability AI FLUX 2.0 Beats Midjourney on Photorealism & Prompt Accuracy',
    description: 'FLUX 2.0 achieves top scores on human preference evaluations, excelling at both photorealistic images and precise prompt following. Available via API at $0.03 per image with batch pricing.',
    source: 'tools',
    sourceLabel: 'AI Tools',
    date: '2026-02-22',
    tags: ['FLUX', 'image AI', 'Stability AI', 'photorealism'],
    url: 'https://stability.ai',
    category: 'Tool Launch',
  },
];
